-
  name: "Wordpress configuration with ansible"
  hosts: local
  tasks: 
    - name: Install packages
      become: true 
      apt:
         name: 
                - nginx
                - mariadb-server
                - mariadb-client
                - php-fpm
                - php-mysql
         update_cache: true
         state: present

